### ISSUE TITLE
Detect apps that shouldn't be public

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/Artemis#210]
easy:
+ esxi panels

hard:
+ networking equipment panels (routers, etc. hard to make comprehensive list)

**Comment by kazet** [comment]
maybe find Gitlab, Jenkins and Kibana as well

**Comment by kazet** [comment]
idrac

**Comment by kazet** [comment]
nuclei exposed-panels supports:
- gitlab,
- jenkins,
- kibana,
- esxi,
- some router panels.

So a TODO would be to add idrac to nuclei
