### ISSUE TITLE
Check for XSS, e.g. using https://github.com/hahwul/dalfox

### ISSUE THREAD

**Issue by kazet** [CERT-Polska/Artemis#248]

**Comment by kazet** [comment]
what is better: xsser or dalfox?

**Comment by cyberamt** [comment]
> what is better: xsser or dalfox?

I have had better experiences with dalfox. [dalfox](https://github.com/hahwul/dalfox) is still being maintained, I think the last commit from [xxser](https://github.com/epsylon/xsser) was 2 years ago.

**Comment by kazet** [comment]
Hello,

thanks for the response! Would you be willing to integrate dalfox into Artemis?

**Comment by cyberamt** [comment]
Yes, i will give it a try 😄

**Comment by kazet** [comment]
Just learned that another contributor is integrating Dalfox into Artemis, so let's avoid duplicating work!
