### ISSUE TITLE
Detect CORS/cross-domain policy that allows interaction from other sites

### ISSUE THREAD

**Issue by kazet** [CERT-Polska/Artemis#300]

**Comment by kazet** [comment]
maybe implementing a Nuclei template is a better idea than an Artemis module

**Comment by kshitijk4poor** [comment]
> if possible, implementing a Nuclei template is a better idea than an Artemis module

https://github.com/projectdiscovery/nuclei-templates/blob/80844c36be078c1e9b6420731447e8b3ca5bf225/http/vulnerabilities/generic/cors-misconfig.yaml#L4

**Comment by kazet** [comment]
Added it to the list of custom modules: https://github.com/CERT-Polska/Artemis/pull/838

Thanks for finding it!
