### ISSUE TITLE
When testing a site check whether s3 buckets and Firebase app for a given name exist

### ISSUE THREAD

**Issue by kazet** [CERT-Polska/Artemis#305]
e.g. we test projectname.example.com

let's check:

s3 bucket projectname
firebase db projectname
s3 bucket projectname-dev
firebase db projectname-dev

etc

**Comment by kshitijk4poor** [comment]
https://github.com/pikpikcu/nuclei-templates/blob/master/subdomain-takeover%2Fs3-subtakeover.yaml
