### ISSUE TITLE
Add information about swarm deployment

### ISSUE THREAD

**Issue by BonusPlay** [CERT-Polska/Artemis#314]
Current docs just say
```
docker compose up --build \
    --scale=karton-nuclei=10 \
    --scale=karton-bruter=10 \
    --scale=karton-port_scanner=10
```
For that to be true, you need to be running a docker swarm, not just docker. This should be documented.

**Comment by kazet** [comment]
IIRC it works for compose in non-swarm mode

**Comment by kazet** [comment]
@BonusPlay do you confirm that it works for compose in non-swarm mode?

**Comment by BonusPlay** [comment]
Yes, it was an issue with old docker compose version.
