### ISSUE TITLE
Getting: WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that! container

### ISSUE THREAD

**Issue by visionarchitect** [CERT-Polska/Artemis#363]
When building using "quick steps" (docker compose)
I am getting: WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that! container  
Solved by changing image to 4.4.6 version

**Comment by kazet** [comment]
duplicate of #264  - there is a PR that will document that as well (https://github.com/CERT-Polska/Artemis/pull/315)
