### ISSUE TITLE
Set custom Authorization Header 

### ISSUE THREAD

**Issue by StasyaPion** [CERT-Polska/Artemis#406]
Hi,
Can I set an Authorization header for the target? I can set the User-Agent header only in the Configuration file.
Should I manually add a variable to the code or is there an option that I've missed? 

Thanks <3

**Comment by kazet** [comment]
Hello, 

sorry for the delay in the response.

Currently such a feature is not implemented. If you want to do that, you need to modify the code. Currently the http requests are performed in the artemis.http_requests module, and beside that, the User-Agent option is passed to tools called by Artemis:
- Nuclei (artemis.modules.nuclei) 
- sqlmap in artemis-modules-extra (https://github.com/CERT-Polska/Artemis-modules-extra/blob/main/karton_sqlmap/karton_sqlmap.py)
