### ISSUE TITLE
Blacklist out of scope hosts

### ISSUE THREAD

**Issue by infosecconsultant** [CERT-Polska/Artemis#428]
Is there a way to blacklist/deny out of scope hosts?

For example:

```
192.168.0.0/24
192.168.1.10-20
192.168.2.4
dev.*.example.local
```

**Comment by kazet** [comment]
Hello,

unfortunately, such a feature is not available yet.

**Comment by kazet** [comment]
Now it is: https://artemis-scanner.readthedocs.io/en/latest/user-guide/configuration.html#blocklist
