### ISSUE TITLE
Consider change default port from 5000 to 8080

### ISSUE THREAD

**Issue by es1o** [CERT-Polska/Artemis#747]
Hi.
Default configuration uses port 5000 to expose artemis web but in MacOS AirPlay uses this port. I changed my configuration to expose 8080 instead.

Maybe this may be changed by default? What do you think?

**Comment by kazet** [comment]
I think port 8080 will also be taken on some configuration. Something random can be a better idea, but as Artemis is already used in a number of configurations, I'd keep 5000 and add the port 5000 issue to the troubleshooting document
