### ISSUE TITLE
ERROR [karton-logger internal] load build context

### ISSUE THREAD

**Issue by kanlukasz** [CERT-Polska/Artemis#753]
Hi,

_( opisuje po angielsku, ale możemy kontynuować po polsku 🇵🇱 )_

### Steps to reproduce:

1. `git clone https://github.com/CERT-Polska/Artemis.git`
2. `cd Artemis`
3. `copy env.example .env`
4. `docker compose up --build`

### Results:
![image](https://github.com/CERT-Polska/Artemis/assets/30685349/ab5ea069-d975-44c2-a510-e5bde517e19f)

### Environment:
- OS Name: Microsoft Windows 11 Pro
- OS Version: 10.0.22631 N/A Build 22631
- Docker version 25.0.1, build 29cf629
- Docker Desktop 4.27.0 (135262) 

### Additional info:
Note that Docker on Windows uses the WSL2
- WSL version: 2.0.14.0
- Kernel version: 5.15.133.1-1
- Debian GNU/Linux 11 (bullseye)

**Comment by ajeden** [comment]
This one is releated to: https://github.com/docker/compose/issues/11421
