### ISSUE TITLE
Improve artemis/modules/data/nuclei_templates_custom/error-based-sql-injection.yaml

### ISSUE THREAD

**Issue by kazet** [CERT-Polska/Artemis#899]
Currently, this Nuclei template detects SQL errors.

We should ensure that on page without injections no error appears to filter out false positives where an error appears always, so there's no SQLi present.

Avoid duplicating the huge list of detected strings.

Detect also: "Uncaught Error: Call to a member function fetch_assoc() on bool"
Inject also `"`, not only `'`
Bonus points: detect time-based SQL injection

**Comment by DelfinSR** [comment]
Are there any examples of these false positives?

**Comment by kazet** [comment]
Sure! Let's assume you have a PHP site that always (regardless of the parameters) run a failed SQL query and prints the error: `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'id = 1' at line 1

**Comment by kazet** [comment]
Detect also http error 500
