### ISSUE TITLE
Unable to export reports

### ISSUE THREAD

**Issue by cloudgitaware** [CERT-Polska/Artemis#962]
I would like to generate reports using the "export" button described here:
https://artemis-scanner.readthedocs.io/en/latest/generating-reports.html#generating-reports

Unfortunately i am unable to see an export button after all tasks have run. Where can i find this button?
Version "latest" tag using docker-compose-file from the repo
Also installed the Artemis-modules-extra repo

**Comment by kazet** [comment]
If you have latest version of Artemis from the repository, you should see the "Export reports" button in the top navigation bar:

![image](https://github.com/CERT-Polska/Artemis/assets/1233067/f6cd18ce-ee7a-4c39-b37a-dda10ef8c8e3)

Do you see it on your instance?

**Comment by cloudgitaware** [comment]
For future reference: i did not see the button. Turns out this is a very recent merge into the repo. So i stopped the docker, removed the images, repulled them and started the docker again. Now i have an Export button.
Thank you!
